import Page, { PageWrapper } from '../components/Page';
import Image from 'next/image'

export default function Email() {
  return (
    <PageWrapper>
      <Page>
        <section className="border-b-stone-500 border-b-2 border-dashed py-8">
          <h1 className="text-xl text-center">DONATION RECEIPT</h1>
        </section>
        <section className="py-8 border-b-stone-500 border-b-2 border-dashed">
          <p className="text-center">
            <span className="font-bold">Heifer International</span>
            <br />
            EIN: 123456789-14 <br />
            123 Fake St <br />
            Buffalo, NZ 12345
          </p>
        </section>
        <section className="py-8 border-b-stone-500 border-b-2 border-dashed px-14">
          <p className="font-bold">February 12, 2022</p>
          <div className="flex justify-between">
            <span className="font-bold">Donation Amount</span>
            <span className="font-bold">1,400 XLM*</span>
          </div>
          <p className="text-sm text-right">
            * XLM is a publicly tradeable crypto-currency with a direct monetary value
          </p>
        </section>
        <section className="py-8 border-b-stone-500 border-b-2 border-dashed px-14">
          <div className="flex justify-between">
            <span className="font-bold">Monetary Value*</span>
            <span className="font-bold">$1,003.72 USD</span>
          </div>
          <p className="text-sm text-right">* At the time of the transaction</p>
        </section>
        <section className="py-8 border-b-stone-500 border-b-2 border-dashed px-14">
          <div className="flex justify-between">
            <span className="font-bold">Donated By</span>
            <span className="font-bold">Evan Hudson</span>
          </div>
        </section>
        <section className="py-8 px-14">
          <p className="text-bold text-center">Thank you for your donation!</p>
          <p className="text-sm text-center">
            No goods or services were provided in exchange for this
            contribution. Heifer International is a tax-exempt 501(c)(3)
            organization.
          </p>
        </section>
      </Page>
      <section className="flex flex-col justify-center align-middle">
        <p className="text-center">Receipt generated by:</p>
        <Image
          src="/LogoV3.png"
          alt="Give XLM Logo"
          className="h-12 self-center"
          width={100}
          height={100}
        />
      </section>
    </PageWrapper>
  );
}
